development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:e613b6e754c056aa85e7133d3723ea37@soldierfish.redistogo.com:11937/
  # channel_prefix: superate_production
